apiVersion: v1
kind: Pod
metadata:
  name: backdoor-demo
spec:
  containers:
    - name: certinject
      volumeMounts:
        - name: mitmproxysecret
          mountPath: /certs
          readOnly: false
      lifecycle:
        postStart:
          exec:
            command:
              - bash
              - -c
              - cp /certs/* /usr/local/share/ca-certificates/ ; update-ca-certificates --fresh
  volumes:
  - name: mitmproxysecret
    secret:
      secretName: mitmproxysecret
