apiVersion: v1
kind: Pod
metadata:
  name: backdoor-demo
spec:
  containers:
    - name: certinject
      volumeMounts:
        - name: mitmproxysecret
          mountPath: /certs
          readOnly: false
      lifecycle:
        postStart:
          exec:
            command:
              - bash
              - -c
              - cp /certs/* /usr/local/share/ca-certificates/ ; update-ca-certificates --fresh
    env:
    - name: http_proxy
      value: "http://mitmproxy-svc.mitmproxy:8080/"
    - name: https_proxy
      value: "http://mitmproxy-svc.mitmproxy:8080/"
    volumeMounts:
    - mountPath: /certs
      name: mitmproxysecret
      readOnly: true
  volumes:
  - name: mitmproxysecret
    secret:
      secretName: mitmproxysecret
