apiVersion: v1
kind: Pod
metadata:
  name: mitm-demo-pod-kustomize
spec:
  containers:
    - name: certinject
    volumeMounts:
    - mountPath: /certs
      name: mitmproxysecret
      readOnly: true
      lifecycle:
        postStart:
          exec:
            command:
              - bash
              - -c
              - cp /certs/* /usr/local/share/ca-certificates/ ; update-ca-certificates --fresh
  volumes:
  - name: mitmproxysecret
    secret:
      secretName: mitmproxysecret
